//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cachero_Color_Game.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=testdatabase.ceeszjwt7h7h.ap-southeast-1.rds.amazonaws.com;Initial Ca" +
            "talog=Group2-RoyalCasino;User ID=admin;Password=password;Connect Timeout=30;Encr" +
            "ypt=False;TrustServerCertificate=False")]
        public string Group2_RoyalCasinoConnectionString {
            get {
                return ((string)(this["Group2_RoyalCasinoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=brent.ceeszjwt7h7h.ap-southeast-1.rds.amazonaws.com;Initial Catalog=\"" +
            "Group 2 - Casino\";User ID=admin;Password=password;Connect Timeout=30;Encrypt=Fal" +
            "se;TrustServerCertificate=False")]
        public string Group_2___CasinoConnectionString {
            get {
                return ((string)(this["Group_2___CasinoConnectionString"]));
            }
        }
    }
}
